# --- Pengaturan Data ---
data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'all'

# --- Pengaturan Model ---
model:
  name: 'layers5_pyramid512_lr0001_wd00001_all'
  hidden_layer_nodes: [512, 256, 128, 64, 32]
  input_shape_factor: 28

# --- Pengaturan Pelatihan ---
training:
  learning_rate: 0.001
  wieght_decay: 0.0001
  epochs: 200
  batch_size: 8192
  early_stopping_patience: 15


